### ISSUE TITLE
caddy-brotli@v1.4.0 ... does not implement encode.Encoder (missing method Flush)

### ISSUE THREAD

**Issue by steffenbusch** [ueffel/caddy-brotli#1]
When trying to build `caddy` with `github.com/ueffel/caddy-brotli` against the caddy `master` branch, the following build error happens:

```
/root/go/pkg/mod/github.com/ueffel/caddy-brotli@v1.4.0/brotli.go:105:10: cannot use brotli.NewWriterV2(nil, b.Level) (value of type *matchfinder.Writer) as encode.Encoder value in return statement: *matchfinder.Writer does not implement encode.Encoder (missing method Flush)
```

Build command was: `/usr/local/bin/xcaddy build master --output /usr/local/bin/caddy --with github.com/ueffel/caddy-brotli`

Most likely related to: https://github.com/caddyserver/caddy/pull/6471

With `caddy-brotli@v1.3.0` it still compiles.

**Comment by ueffel** [comment]
Hmm `Flush() error` is required now for encoder modules. The upstream brotli module does not implement a flush in the new matchfinder algorithm writer <https://pkg.go.dev/github.com/andybalholm/brotli@v1.1.0/matchfinder#Writer>.
I could

1. just wrap the writer and add a No-Op flush method, which is kinda bad or
1. revert the matchfinder algorithm stuff or
1. open an issue upstream

🤔

**Comment by steffenbusch** [comment]
If the `NewWriterLevel` had the `Flush() error`, maybe it's just an oversight that the `NewWriterV2` is missing this.

**Comment by ueffel** [comment]
It's not an oversight, see <https://github.com/andybalholm/brotli/issues/53>. I'm reverting the addition of the new algorithm.

Without flushing, it doesn't make a lot of sense to keep it for encoding dynamic content. Zstd or gzip are better for dynamic content anyways.
